FRAMES_DIR: ./frames
ANNOTATED_FRAMES_DIR: ./anno_frames
LABELS_DIR: ./labels
VIDEO_DIR: ./videos
ORIGINAL_DIR: ./yolo_dsort

FILTERED_CLASSES: None

SAVE_RAW: False
SAVE_ORIGINAL: False
DISPLAY_ORIGINAL: False
SAVE_ANNOTATED_FRAMES: False

X_SIZE: 1280
Y_SIZE: 720
