FRAMES_DIR: ./data/frames
ANNOTATED_FRAMES_DIR: ./data/anno_frames
LABELS_DIR: ./data/labels
EDITED_LABELS_DIR: ./data/edited_labels
VIDEO_DIR: ./videos
ORIGINAL_DIR: ./data/yolo_dsort

FILTERED_CLASSES: None

SAVE_RAW: False  # if True save raw frames
SAVE_ORIGINAL: False  # if True saves tracker+detection outputs as a seperate video
DISPLAY_ORIGINAL: False
SAVE_EDITED_FRAMES: False
SAVE_NON_EDITED_FRAMES: False

REAL_TIME: True

ID_TO_CLASS_CFG: temp_class_list.yaml
ID_TO_COLOR_CFG: temp_color_list.yaml
KEY_TO_CLASS_CFG: key_to_class.yaml


X_SIZE: 1920
Y_SIZE: 1080
