FRAMES_DIR: ./data/frames  # where to save all frames
ANNOTATED_FRAMES_DIR: ./send_data/anno_frames  # where to save annotated frames by the user
LABELS_DIR: ./data/labels  # where to save all labels
ANNOTATED_LABELS_DIR: ./send_data/anno_labels  # where to save labels for annotated frames by the user
VIDEO_DIR: ./videos
ORIGINAL_DIR: ./data/yolo_dsort  # where to save yolo+deepsort applid video file, SAVE_ORIGINAL must be true

FILTERED_CLASSES: None  # if None detect all classes, else detected classes belonging to given ids

SAVE_RAW: False  # if True save raw frames in a seperate dir
SAVE_EDITED_FRAMES: True  # if True, save annotated frames and labels to disk

SAVE_ORIGINAL: False  # if True saves tracker+detection outputs as a seperate video
DISPLAY_ORIGINAL: False  # if True display yolo+deepsort annotated video in a seperate video

REAL_TIME: False

ID_TO_CLASS_CFG: class_list.yaml
ID_TO_COLOR_CFG: color_list.yaml
KEY_TO_CLASS_CFG: key_to_class_w32.yaml

X_SIZE: 1080
Y_SIZE: 720

# network
HOST: '192.168.0.0'
PORT: 65432
FOLDER_SENT: ./send_data


